version: '2'

services:

  postgres:
    image: 'postgres:12'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: reportingdb
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root